apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-metrics
  name: node-metrics
  namespace: crane-system
spec:
  selector:
    matchLabels:
      app: node-metrics
  template:
    metadata:
      labels:
        app: node-metrics
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/hexiaoshi/node-metrics:0.0.1
        name: node-metrics
        args:
        - --web.listen-address=0.0.0.0:19101
        volumeMounts:
          - mountPath: /run/containerd/containerd.sock
            name: containerd
        resources:
          limits:
            cpu: 102m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
      hostNetwork: true
      hostPID: true
      volumes:
        - hostPath:
            path: /run/containerd/containerd.sock
            type: 'Socket'
          name: containerd          